/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f429xx_adc.h"
#include "stm32f429xx_gpio.h"

adc_handle_t hadc1;
gpio_handle_t hgpioa;

void adc_configure(void);
void gpio_configure(void);

int main(void) {

	adc_configure();
	adc_poll_for_convesion(&hadc1);
	uint16_t adc_ret_val = adc_get_regular_val(&hadc1);
	UNUSED(adc_ret_val);

    /* Loop forever */
	for(;;) {

	}
}

void adc_configure(void) {
	hadc1.adc_config.adc_mode = ADC_MODE_SINGLE_ENDED;
	adc_init(&hadc1);

	adc_channel_config(&hadc1);
}

void gpio_configure(void) {
	// ADC ch1 gpio config
	hgpioa.pgpio = GPIOA;
	hgpioa.gpio_config.gpio_pin = GPIO_PIN_0;
	hgpioa.gpio_config.gpio_mode = GPIO_MODE_ANALOG;
	hgpioa.gpio_config.gpio_pupdr = GPIO_PUPD_NO;
	gpio_init(&hgpioa);
}
