/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f429xx_gpio.h"

gpio_handle_t pgpiohandle;

void gpio_configure(void);
void delay(void);

int main(void)
{
	gpio_configure();


    /* Loop forever */
	for(;;) {
		gpio_write_pin(GPIOB, GPIO_PIN_7, GPIO_HIGH);
		delay();
		gpio_write_pin(GPIOB, GPIO_PIN_7, GPIO_LOW);
		delay();
	}
}

void gpio_configure(void) {
	RCC_GPIOB_CLK_EN();

	pgpiohandle.pgpio = GPIOB;
	pgpiohandle.gpio_config.gpio_mode = GPIO_MODE_OUTPUT;
	pgpiohandle.gpio_config.gpio_optype = GPIO_OPTYPE_PP;
	pgpiohandle.gpio_config.gpio_opspeed = GPIO_OSPEED_LOW;
	pgpiohandle.gpio_config.gpio_pin = GPIO_PIN_7;
	pgpiohandle.gpio_config.gpio_pupdr = GPIO_PUPD_NO;

	gpio_init(&pgpiohandle);
}

void delay(void) {
	for (int i = 0; i < 500000; i++){}
}

